# Generated by Django 3.0.3 on 2020-11-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
