# Generated by Django 3.0.3 on 2020-11-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_android'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('QQ', models.CharField(max_length=32)),
                ('WeChat', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('service', models.CharField(max_length=32)),
                ('os_version', models.CharField(max_length=32)),
                ('formating', models.CharField(max_length=32)),
                ('software', models.CharField(max_length=32)),
                ('update', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Android',
        ),
    ]
