# Generated by Django 3.0.3 on 2020-11-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_auto_20201120_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reservation_list',
        ),
    ]
