# Generated by Django 3.0.3 on 2020-11-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FirstApp', '0005_delete_reservation_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=2)),
                ('s_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('college', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=32)),
                ('recived_list', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='reservation_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('QQ', models.CharField(max_length=32)),
                ('WeChat', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('service', models.CharField(max_length=32)),
                ('os_version', models.CharField(max_length=32)),
                ('formating', models.CharField(max_length=32)),
                ('software', models.CharField(max_length=32)),
                ('update', models.CharField(max_length=32)),
            ],
        ),
    ]
