# Generated by Django 3.0.3 on 2020-11-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_register_list_reservation_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_list',
            name='action',
        ),
        migrations.RemoveField(
            model_name='reservation_list',
            name='action',
        ),
    ]
