# Generated by Django 3.1.3 on 2020-11-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_auto_20201120_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='seekHelp_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=32)),
                ('discuss_list', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='watchHour_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id_list', models.CharField(max_length=32)),
                ('odd_or_even', models.CharField(max_length=32)),
                ('week', models.CharField(max_length=32)),
                ('time_slot', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='register_list',
            old_name='recived_list',
            new_name='campus',
        ),
        migrations.RenameField(
            model_name='register_list',
            old_name='school',
            new_name='received_list',
        ),
    ]
